name: Deploy to DigitalOcean

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/slack-mcp-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/slack-mcp-server:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action@main
      with:
        app_name: ${{ secrets.DIGITALOCEAN_APP_NAME }}
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: |
          [
            {
              "name": "slack-mcp-server",
              "registry_type": "DOCR",
              "registry": "${{ env.REGISTRY }}",
              "repository": "${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/slack-mcp-server",
              "tag": "${{ github.sha }}"
            }
          ] 